### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by tommytroylin** [nowa-webpack/nowa2#1]
## 1.0 Release Late June 2018

Ordered by priority

### development

- [X] @nowa/module-webpack support webpack 4.0
- [ ] @nowa/module-babel
- [ ] @nowa/module-template
- [ ] @nowa/module-rollup
- [ ] @nowa/create

### internal changes & refactor

- [X] ts 2.9
- [ ] tapable
- [ ] simplified types.ts

### solutions

- [ ] @nowa/solution-react wait for create-react-app supporting webpack 4
- [ ] @nowa/solution-vue
- [ ] @nowa/solution-node-package

### docs

- [ ] markdowns move to github
- [ ] @nowa/solution-react introduction
- [ ] creating & modifying solution 
- [ ] @nowa/create introduction (aka nowa init)
- [ ] generate website
